name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix
          extraPullNames: johngavin
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Push Project R Package to Cachix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix-shell --keep CACHIX_AUTH_TOKEN --run "
            set -e
            echo 'Building project R package as Nix derivation...'
            nix-build package.nix
            result_path=$(readlink -f result)
            echo 'Pushing $result_path to johngavin cache...'
            cachix push johngavin '$result_path'
          "

      - name: Build and Pin Nix Shell
        run: |
          GC_ROOT_PATH=/nix/var/nix/gcroots/per-user/$USER/$(basename ${{ github.repository }})-ci-shell
          mkdir -p $(dirname $GC_ROOT_PATH) # Ensure parent directory exists
          nix-build default.nix -A shell -o "$GC_ROOT_PATH" --cores 8 --quiet
          if [ $? -ne 0 ]; then
              echo "ERROR: nix-build failed."
              exit 1
          fi
          echo "GC Root created at $GC_ROOT_PATH"

      - name: Run R Verification
        run: |
          nix-shell ./default.nix --run "
            set -e
            echo 'Nix environment ready with GC root'
            R_LIBS_SITE=\"$(Rscript -e 'cat(.libPaths()[1])')\" Rscript R/setup/ci_verification.R
          "

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-results
          path: check
