name: test-coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix
          extraPullNames: johngavin
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build nix environment
        run: nix-shell --run "echo 'Nix environment ready'"

      - name: Build and Pin Nix Shell
        run: |
          GC_ROOT_PATH=/nix/var/nix/gcroots/per-user/$USER/$(basename ${{ github.repository }})-ci-test-coverage-shell
          mkdir -p $(dirname $GC_ROOT_PATH) # Ensure parent directory exists
          nix-build default.nix -A shell -o "$GC_ROOT_PATH" --cores 8 --quiet
          if [ $? -ne 0 ]; then
              echo "ERROR: nix-build failed."
              exit 1
          fi
          echo "GC Root created at $GC_ROOT_PATH"

      - name: Test coverage
        run: |
          nix-shell --run "
            set -e
            echo 'Nix environment ready with GC root'
            R_LIBS_SITE=\"$(Rscript -e 'cat(.libPaths()[1])')\" Rscript -e 'covr::codecov(
              quiet = FALSE,
              clean = FALSE,
              token = \"${{ secrets.CODECOV_TOKEN }}\"
            )'
          "

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
